# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pool_skillpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(default='', max_length=50)),
                ('percentage', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
