# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_servicepluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('phone', models.CharField(max_length=45)),
                ('attachment', models.FileField(upload_to=b'')),
            ],
        ),
    ]
